# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ac644fbdfd05998cbeda19b07ca43c2d15f49c0a966cad668fdcfd1a751db486b7c9fe48578143a3d9585b9ad5f796a781b33a53b7d35041256c2eef8cbb75

test:
  secret_key_base: 006ed2fa655fd9b14ebe76faa74ce04850027566633526fa8e2af4a0f5bb99380d09468a5810cd5b3d95c9324da3c9a1fefb196150103f044f91f84fc9195178

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
